### ISSUE TITLE
快速删除列表导致崩溃

### ISSUE THREAD

**Issue by txdxxl** [ccseer/PinStack#1]
由于现在没有清空列表的功能，只好用ctrl+D删除，按住ctrl+d不放，删除多条列表（大概20条）以后，程序崩溃关闭

**Comment by ccseer** [comment]
🙏谢谢

感谢反馈

应该是动画效果跟不上。。下个版本改

txdxxl <notifications@github.com>于2017年7月3日周一 下午4:44写道：

**Comment by ccseer** [comment]
不过为啥要清空。
你可以去把数据文件删了
在 AppData/Local/Corey/PinStack
我这边的完整路径是 c:/Users/Corey/AppData/Local/Corey/PinStack

Corey Chan <cc.seer@gmail.com>于2017年7月3日周一 下午5:03写道：

**Comment by txdxxl** [comment]
清空或者批量删除的场景有2个：
1.在公司或者家庭电脑里，一些复制的记录不想被看到；
2.复制多了列表太长，找以前的数据困难（现在windows下，用滚轮下滑列表的体验很不好，阻滞感太强）

**Comment by ccseer** [comment]
好. 下个版本加个快捷键直接清空

滚轮的问题下个版本想办法改进吧...

**Comment by ccseer** [comment]
fixed。
快速删除崩溃和快捷键清空的快捷键。


需要的话可以给我发邮件啊～

**Comment by txdxxl** [comment]
OK，最近出差刚回来，下载有点慢，我先转支付宝吧，下载好了发码

**Comment by txdxxl** [comment]
还是1.0.1啊？

**Comment by ccseer** [comment]
没发布啊。

没这么快。
你需要的话我可以先邮箱发给你。
没人喜欢频繁更新吧。



txdxxl <notifications@github.com>于2017年7月9日周日 下午3:22写道：

**Comment by txdxxl** [comment]
发我邮箱吧，我在官网下了一下午没下下来。。。

**Comment by ccseer** [comment]
呃。。

1.0.1 可以从这里下载： https://1drv.ms/u/s!AgtA1EcmfJYVjMd13esnTZxYqRA41g

这个bug的修复版得等明天了。
现在在家里，os x 下改的。明天去公司编译一个就可以了。



txdxxl <notifications@github.com>于2017年7月9日周日 下午4:02写道：

**Comment by ccseer** [comment]
[PinStack.zip](https://github.com/ccseer/PinStack/files/1134319/PinStack.zip)

放到执行文件目录里就可以了....

**Comment by ccseer** [comment]
滚轮的问题   好像可以了.... 

你看看滚轮是不是还有问题啊?

**Comment by txdxxl** [comment]
滚轮的问题解决了，长按ctrl+D快速删除依然崩溃。。

**Comment by ccseer** [comment]
[自杀.jpg]

**Comment by ccseer** [comment]
你先用快捷键删除吧 . . 在配置里 可以看到

**Comment by ccseer** [comment]
我在 pin view 里面要加一个新的内容。数据格式变了。 所以你用的是还在开发的版本。

然后......................可能没法保存数据。

**Comment by txdxxl** [comment]
没办法保存数据时说重启软件会被清空？

**Comment by ccseer** [comment]
对啊...

**Comment by ccseer** [comment]
发布的时候会兼容老数据的。

只是目前还在做这一块

**Comment by txdxxl** [comment]
那还是。。。可以暂时忍受，一般软件自启动以后就开一天，第二天也很少会用到上次的数据

**Comment by ccseer** [comment]
现在是 按下 + 弹起  一个按键操作做一次响应了..
不然动画跟不上

**Comment by ccseer** [comment]
还剩一些联机的功能要改... 改完就可以发布了

谢谢
