### ISSUE TITLE
it will crash sometimes in my mac

### ISSUE THREAD

**Issue by warwr1ck** [ccseer/PinStack#12]
i dont know how,but it will crash sometimes.
and one advice, i think it will be more comfortable if the icon is the same style of others.
please forgive my pool english.
![image](https://user-images.githubusercontent.com/14226761/55768389-4ed6fe00-5aaf-11e9-93da-29d6d589b371.png)

**Comment by ccseer** [comment]
新版本三天内就能写完了

Logo 的问题我再看看吧，需要联系设计师才行

**Comment by ccseer** [comment]
有没有 crash 的复现步骤?

**Comment by warwr1ck** [comment]
我设置了显示剪贴板窗口的快捷键，shit + command + c，不知道是不是快捷键冲突的问题……
有时候mac待机很久之后，再次启动会crash掉
具体的我再留意一下，之后返回

**Comment by ccseer** [comment]
已发布.
再有问题再打开吧
