### ISSUE TITLE
Windows7 版本出现黑框

### ISSUE THREAD

**Issue by ZhangHowie** [ccseer/PinStack#13]
软件周围出现了一圈黑色框框
![image](https://user-images.githubusercontent.com/18179774/71469082-0e690d00-2803-11ea-9c13-d759eb575425.png)

**Comment by ccseer** [comment]
抱歉。
一般和显卡驱动有关。
下个版本更新大概能解决。
春节后吧大概

**Comment by ZhangHowie** [comment]
好的

**Comment by ccseer** [comment]
可以更新了试下。
再不行就只能退款啊
:(
