### ISSUE TITLE
功能上的一些建议

### ISSUE THREAD

**Issue by tuihou123321** [ccseer/PinStack#18]
一、选中的文本不能通过enter键输出在页面上
![image](https://user-images.githubusercontent.com/7146036/140632961-f06cf8a2-373f-4c00-a5a4-fc91ade7b66a.png)

二、剪贴版的内容不能编辑

三、不支持合并粘贴

四，不支持剪贴版选中删除

-----

ditto是目前使用体验最好的软件

**Comment by ccseer** [comment]
1 双击列表项
2 这个大概率不会做
3 需要按住Ctrl后多选
4 Ctrl+D. 快捷键列表在设置页面里，下拉后有个按钮可以看到。

这个软件确实很久没更新了。下个月圣诞节放寒假了估计才有时间。不过由于计划一次大改，不一定能短期内做完

**Comment by ccseer** [comment]
第一个使用回车可以吧。
不能得原因需要 输出得那个程序 和 PinStack 有相同得权限。如果那个程序是管理员，PinStack 不是，那就不行

**Comment by ccseer** [comment]
新版本发布了

第二个不会做C
第三个之前做了,现在删除了,以后也不会做

中文反馈换地方了
https://support.qq.com/products/414197
