### ISSUE TITLE
快捷键设置问题

### ISSUE THREAD

**Issue by gemini11317** [ccseer/PinStack#2]
我之前一直用ditt，所以习惯快捷键是ctrl+`但是在pinstack当中设置成功以后按下ctrl+`没有任何反应。

**Comment by ccseer** [comment]
你是说 ctrl和+ 组合？

**Comment by gemini11317** [comment]
@ccseer 是的 ctrl+ 的组合键方式

**Comment by ccseer** [comment]
我明天试试再看吧

我现在在 mac 上没啥问题



gemini11317 <notifications@github.com>于2017年7月16日周日 下午10:27写道：

**Comment by gemini11317** [comment]
@ccseer 好的，我使用的是win10 pro 1703

**Comment by ccseer** [comment]
问题是这样的

你是按的数字键旁边的  + 号. 那个东西 你在文本编辑器里输入的时候显示是个 = 号.
如果你在设置快捷键的时候用的是 小键盘的 + 号 , 是工作正常的.

**Comment by ccseer** [comment]
要在 +/=  那个地方输入 + 号需要按 shift. 

但是 在输入快捷键的时候, shift 也是修辞键

**Comment by gemini11317** [comment]
好的明白了，问题解决了。thx
