### ISSUE TITLE
希望也可以有手机版，方便手机电脑的复制内容互相访问

### ISSUE THREAD

**Issue by JinZhou117** [ccseer/PinStack#20]

**Comment by ccseer** [comment]
呃。。。。新版本数据共享功能已经删了。

**Comment by ccseer** [comment]
下个月就能发布了。重写了一半的内容。

**Comment by ccseer** [comment]
我当初想要的只是 一个界面好看一点然后能从已复制内容中复制部分文字 的 系统剪贴板替代工具。

**Comment by ccseer** [comment]
新版本发布了

https://support.qq.com/products/414197
