### ISSUE TITLE
语言无法切换为中文

### ISSUE THREAD

**Issue by Flyfish233** [ccseer/PinStack#22]
Windows 显示语言是中文，安装了中文和英语的语言包。打开应用后默认为英语，进入设置选中中文后点选 RESTART，仍然提示 Application Started 的通知，界面仍为英语。此时至设置打开简体中文，重启后仍然重置为英语。重启系统无效。

**Comment by ccseer** [comment]
看上去像是没办法写 配置文件.  你是不是 修改 程序 默认目录了。

**Comment by Flyfish233** [comment]
已解决，修改了程序默认目录
