### ISSUE TITLE
windows商店下载后，无法启动

### ISSUE THREAD

**Issue by UlaEve** [ccseer/PinStack#23]
如题，进程短暂启动后退出，无法启动到程序界面。
![image](https://user-images.githubusercontent.com/92962690/190972678-2312d204-f48e-408b-8d16-82a1dc8072ad.png)
重装软件、重置windows store无法解决

**Comment by ccseer** [comment]
我 邮件 回复你了。。 感觉大概率是 显卡驱动的问题。

**Comment by ccseer** [comment]
更新了, 估计可以了
1.9.2
