### ISSUE TITLE
无法切换成中文

### ISSUE THREAD

**Issue by Kronight** [ccseer/PinStack#26]
WIN11的笔记本可以,WIN10的不行
![屏幕截图 2023-06-06 231301](https://github.com/ccseer/PinStack/assets/76555141/60afbe19-b5e4-4411-90b4-18ec6424e40d)

**Comment by ccseer** [comment]
等下个版本发布吧。是不是换过软件安装位置，导致程序没办法写配置。
下个版本能解决，不过我也不确定下个版本什么时候发布。

**Comment by ccseer** [comment]
在  文档/Documents 文件夹下, 新建一个目录 PinStack, 然后新建一个空文本文件 uwp.ini
再重启软件就好了
