### ISSUE TITLE
提一些个人的意见

### ISSUE THREAD

**Issue by Pengyou0926** [ccseer/PinStack#27]
1. 转换为颜色的点击操作无效，且完成点击后会自动跳转至最上方复制的内容。
2. 当鼠标移动至复制的内容时，格式会发生变化，此情况由复制和 pin 的按钮相互挤压所致，个人认为按钮可设置为悬浮于最上层。
3. 每条内容之间能否添加一个隔断？例如横线之类。
4. 点击清除格式后，会自动重新复制一次，此操作略显多余，并且期望能够增加撤回清除格式的操作。
5. 查找置于（文本/图片/文件）按钮下方或许更为适宜。因为在拖动窗口时，会点击到输入框，从而导致无法拖动。

此为个人意见！软件甚为好用，我是从 ditto 转用而来的，美观程度搞几个档。

**Comment by ccseer** [comment]
https://support.qq.com/embed/phone/414197/post/172362610118172805/

新版本已经在审核了。
下个版本看看吧

**Comment by ccseer** [comment]
感谢反馈

**Comment by ccseer** [comment]
> 每条内容之间能否添加一个隔断？例如横线之类。
新版本加了间隔，看起来好些了

> 点击清除格式后，会自动重新复制一次，此操作略显多余，并且期望能够增加撤回清除格式的操作。
复制的东西都会保留原格式，然后在操作上添加新的数据。不想去改原数据。

> 查找置于（文本/图片/文件）按钮下方或许更为适宜。因为在拖动窗口时，会点击到输入框，从而导致无法拖动
界面改了。把标题栏留了出来。
