### ISSUE TITLE
选项“隐藏窗口当”设置为“手动关闭”时在面板双击或使用Enter无法粘贴

### ISSUE THREAD

**Issue by whaleday** [ccseer/PinStack#28]
版本：Windows Store 1.9.2U
希望修复一下这个问题，感谢。

**Comment by ccseer** [comment]
你怎么操作的，我刚试了下 工作正常。
![img_v3_02gh_7b2b6c30-1ffd-4466-a7ff-38260bc1a9cg](https://github.com/user-attachments/assets/1473642e-b74e-4fd8-910a-9b40508eccf1)

**Comment by ccseer** [comment]
有时候需要下一个有焦点的程序 运行权限不是更高。 如果是管理员， 而PinStack 不是，就会失败。

**Comment by ccseer** [comment]
改了一点。 发布了再试下吧

**Comment by ccseer** [comment]
更新了再试下吧
