### ISSUE TITLE
CPU 占用异常的高

### ISSUE THREAD

**Issue by sustain86** [ccseer/PinStack#3]
显示剪贴板窗口后，滑动滚轮看之前的内容， PinStack 的 CPU 就会急剧升高，卡到不能用。
PinStack 版本 : 1.1  
Windows：10. 0.15063.0

**Comment by coooooooorey** [comment]
然后就卡死了？

完了之后会降下来吗？

**Comment by ccseer** [comment]
然后就卡死了？

完了之后会降下来吗？

**Comment by sustain86** [comment]
卡死了，只有从任务管理器结束任务。

**Comment by ccseer** [comment]
好

偶发对吧？

我工作日每天也用的比较多，还没碰到

我晚点查查～

谢谢反馈

sustain86 <notifications@github.com>于2017年9月2日周六 下午7:20写道：

**Comment by sustain86** [comment]
最近几天使用一直都是这样，应该不是偶发性的。每次滑动到一半都会卡一下，然后 CPU 这里就是31%，再操作就卡死。

**Comment by sustain86** [comment]
因为缺少一些以 dll 结尾的文件，安装不成功，我等下一版吧。

**Comment by ccseer** [comment]
呃……
好吧
其实这不是安装包，只是执行文件，替换安装文件夹里的那个exe就可以了

那我尽快吧

**Comment by sustain86** [comment]
替换了还是不行。

**Comment by ccseer** [comment]
好吧。 Sorry。

现在在家里了。。没 Windows 环境。那就我忙完 上架的事尽快来改吧。

sustain86 <notifications@github.com>于2017年9月6日周三 下午10:53写道：

**Comment by sustain86** [comment]
好的。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ccseer** [comment]
1.4 应该修复了

**Comment by ccseer** [comment]
如果还出现再打开
