### ISSUE TITLE
Show Images by Default

### ISSUE THREAD

**Issue by lloyd094** [ccseer/PinStack#5]
Unless it's supposed to work like this, _can there be an option to show files automatically as a visual_ (.jpg as a picture, not a file location; .pdf as the pdf render, not just the path).

While it may require more space taken by the program (storage, ram, cpu), I think the option to allow would be much more fluid and overall a nicer product in the end.

**Comment by ccseer** [comment]
You can preview the file path by the "Eye" btn

![image](https://user-images.githubusercontent.com/15963166/37959883-c6648bb0-31e6-11e8-862a-deafa34456b8.png)

**Comment by ccseer** [comment]
The button will preview the file via Seer(Win) or Quick look(macOS)

**Comment by lloyd094** [comment]
When the text on the right show `image`, it shows the picture, but I do not have the option for the eye icon. (v1.2.0)

![image](https://user-images.githubusercontent.com/22482891/37992213-e73a1282-31bf-11e8-883b-f40171d0d85f.png)

**Comment by ccseer** [comment]
fixed in 1.6.0
