### ISSUE TITLE
Alpha Transparency Issues

### ISSUE THREAD

**Issue by lloyd094** [ccseer/PinStack#6]
Some content (for example, copied words from websites) have an alpha layer issue, that seems to show everything behind the letters in the clipboard view. Below is an example of the wording, and showing what's behind.

![capture](https://user-images.githubusercontent.com/22482891/36230326-eda01884-118e-11e8-9575-3ab6304fe358.PNG)

**Comment by ccseer** [comment]
#8 It's the same problem
