### ISSUE TITLE
Pinned Quick Paste Issue

### ISSUE THREAD

**Issue by lloyd094** [ccseer/PinStack#7]
Sometimes when using the quick paste `Ctrl + Alt + V`, and selecting a Pinned clip (from screen 2), I get whatever is from the main screen (screen 1). When this happens, I can usually fix it by going from screen 2 to screen 1, then back to screen 2.

EDIT: Upon more testing (and video), it appears that PinStack has issues switching between the two screens. See the video to get a visual representation.

https://1drv.ms/v/s!AoxDqDueukBSidg_6edWsemWf75gzg

**Comment by ccseer** [comment]
Thank you for the info you provided. 
It's very useful.

**Comment by ccseer** [comment]
I will fix it in next version
