### ISSUE TITLE
Support Word Text Boxes

### ISSUE THREAD

**Issue by lloyd094** [ccseer/PinStack#8]
When using MS Word, PinStack will not "note down" or add a copied text box to the list. I can still copy/paste, but if I use PinStack to paste something else, the text box is forgotten.

**Comment by ccseer** [comment]
I tested it, the text from MS Word is marked by HTML

**Comment by ccseer** [comment]
and some properties is written in global CSS, the fragment we copy from MS Word doesn't contain the global CSS.

**Comment by lloyd094** [comment]
Is there a way for PinStack to render a view, or convert to a visible view? Perhaps a plug-in?

**Comment by ccseer** [comment]
Actually  I don't think it's possible.
The copied  contents  is controlled by the original APP where you press "Ctrl+C"

**Comment by lloyd094** [comment]
Interesting - hopefully in the future there will be a solution for this, but until then I'll consider this closed I guess. Thanks.
