### ISSUE TITLE
Quick Paste Screen Option

### ISSUE THREAD

**Issue by lloyd094** [ccseer/PinStack#9]
For my normal workflow, I find myself using the "pinned snippets" significantly more than the standard clipboard, but I have to constantly use `Ctrl+Alt+V` followed by the over arrow to get to the pins. Can you make an option to either:

1. **Remember which screen was on last** (if I used a pinned content, next time I open the quick paste it's in the pinned content screen, not the paste list)
_OR_
2. **Set default quick-paste screen** (so I could set it to the pinned content to pop up when I open quick-paste)

Both could also work, but this seems like it could help significantly in work flow, and make a better product in the end.

**Comment by ccseer** [comment]
Hi
https://1drv.ms/u/s!AgtA1EcmfJYVkM9VWGXRh8axhDqbjA

Would you please help me to check if everything works well?
I will release it in 12 hours if you say yes.

![image](https://user-images.githubusercontent.com/15963166/38134462-bed5d488-3445-11e8-853f-256df6649123.png)

**Comment by ccseer** [comment]
it's exe file you need to put it into the installation folder

**Comment by ccseer** [comment]
And please close the issue if it doesn't exist : )

cheers

**Comment by lloyd094** [comment]
Unfortunately I can't check this, because I'm using the version from the Windows Store (the folders are locked). Is there an alternative to give it a go?

**Comment by lloyd094** [comment]
You're a wizard 👍 Thank you!
